# Use the SDK image for development, as it includes all necessary tools
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS development

# Set the working directory inside the container
WORKDIR /app

# Expose the ports your application uses
EXPOSE 5008

# Core Services
COPY ["BuildingBlocks/CQRS.Core/CQRS.Core.csproj", "BuildingBlocks/CQRS.Core/"]
COPY ["BuildingBlocks/Daikon.Events/Daikon.Events.csproj", "BuildingBlocks/Daikon.Events/"]
COPY ["BuildingBlocks/Daikon.EventStore/Daikon.EventStore.csproj", "BuildingBlocks/Daikon.EventStore/"]
COPY ["BuildingBlocks/Daikon.Shared/Daikon.Shared.csproj", "BuildingBlocks/Daikon.Shared/"]


# Questionnaire Services
COPY ["Services/Questionnaire/Questionnaire.API/Questionnaire.API.csproj", "Services/Questionnaire/Questionnaire.API/"]
COPY ["Services/Questionnaire/Questionnaire.Application/Questionnaire.Application.csproj", "Services/Questionnaire/Questionnaire.Application/"]
COPY ["Services/Questionnaire/Questionnaire.Domain/Questionnaire.Domain.csproj", "Services/Questionnaire/Questionnaire.Domain/"]
COPY ["Services/Questionnaire/Questionnaire.Infrastructure/Questionnaire.Infrastructure.csproj", "Services/Questionnaire/Questionnaire.Infrastructure/"]

RUN dotnet restore "Services/Questionnaire/Questionnaire.API/Questionnaire.API.csproj"
COPY . .

WORKDIR "/app/Services/Questionnaire/Questionnaire.API"

# Entry point for the application
ENTRYPOINT ["dotnet", "watch", "run"]
